version: 0.2
env:
  secrets-manager:  
    AWS_ACCESS_KEY_ID_SECRET: /terraform/dev/AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY_SECRET: /terraform/dev/AWS_SECRET_ACCESS_KEY
phases:
  install:
    commands:
      - echo "Starting the build"
      - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update && sudo apt install terraform
      - terraform version  # Verify Terraform installation
      - ls #verify repo/files
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /root/.bashrc
      - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - brew install terragrunt
      - sudo apt-get install build-essential
      - terragrunt --version #verify terragrunt installation
  build:
    commands:
      - echo "Running Terragrunt Apply"
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_SECRET
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_SECRET
      - cd environments/Dev/zabbix/
      - terragrunt apply --auto-approve # Launch terragrunt apply with auto approve flag
      - terragrunt show -json > terragrunt_show.json  # Output show (current state after deploy) to a JSON file
      - echo "searching for SSH key"
      - export SSH_KEY_NAME="ec2_SSH_Key.pem"
      - find . -name "$SSH_KEY_NAME*" -print | head -n 1
  post_build:
    commands:
      - echo "Searching for SSH key"
      - find . -name "ec2_SSH_Key.pem" -print  # Find the SSH key in the build environment
      - mkdir -p artifacts  # Create a folder to store artifacts
      - KEY_PATH=$(find . -name "ec2_SSH_Key.pem" -print | head -n 1)  # Get the first match
      - if [[ -n "${KEY_PATH}" ]]; then cp "${KEY_PATH}" artifacts/; else echo "SSH key not found"; fi  # Copy the SSH key to artifacts if found
artifacts:
  files:
    - environments/Dev/zabbix/terragrunt_show.json # Save the output JSON file as an artifact
    - "artifacts/*"  # Include all files in the artifacts folder      
